# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20180515_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(default='科技', max_length=20, verbose_name='项目分类')),
            ],
            options={
                'verbose_name': '项目分类属性表',
                'verbose_name_plural': '项目分类属性表',
            },
        ),
        migrations.CreateModel(
            name='Tage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tage_type', models.CharField(default='手机', max_length=10, verbose_name='项目标签')),
            ],
            options={
                'verbose_name': '项目标签属性表',
                'verbose_name_plural': '项目标签属性表',
            },
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='tage',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='category_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Category', verbose_name='项目所属分类'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='tage_type',
            field=models.ManyToManyField(default=1, to='project.Tage', verbose_name='项目所属标签'),
        ),
    ]
