# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20180515_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='tage_type',
        ),
        migrations.AddField(
            model_name='tage',
            name='project',
            field=models.ManyToManyField(default=1, to='project.ProjectInfo', verbose_name='项目'),
        ),
    ]
