# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20180518_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='active_status',
            field=models.CharField(choices=[('2', '众筹成功'), ('1', '众筹中'), ('0', '即将开始')], default='0', max_length=10, verbose_name='项目众筹状态'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='check_status',
            field=models.CharField(choices=[('2', '审核未通过'), ('1', '审核通过'), ('0', '审核中')], default='0', max_length=10, verbose_name='项目审核状态'),
        ),
    ]
